### PR TITLE
RES-182 cache issues followup

### PR DESCRIPTION
**Pull request by oxtopus**
- Reports warning if `json.loads()` is supressed
- Adds test cases specific to desired cache behavior
- Minor bugfix re: default values to `_placeholderFingerprint()`

### CODE REVIEW

**Comment by subutai** [comment]
:+1: Can you also manually test with something like:

```
python simple_labels.py --dataPath ~/nta/grok-projects/nlp_experiments/yale/buckets/yale_data_buckets_ints.csv -m htm --numLabels 10 -c data/network_configs/sensor_simple_tp_knn.json 
```

The first invocation should take a while to run. The second time should not incur any HTTP requests.

**Comment by subutai** [comment]
And you should get accuracy around 99%

**Comment by oxtopus** [comment]
Good suggestion, @subutai!  It turns out there was a subtle bug that was subverting the caching mechanism in `getTextBitmap()`.  With the bugfix in place, here are the results.

First run, with no cache:

```
Total correct = 365 out of 367 documents
Accuracy = 99.4550408719 %

Profiling information for ClassificationModelHTM
+------------+---------+-----------+----------------+------------------+
| Region     | Count   |   Elapsed |   Pct of total |   Secs/iteration |
+============+=========+===========+================+==================+
| classifier | 29943   |   653.477 |         29.600 |            0.022 |
+------------+---------+-----------+----------------+------------------+
| sensor     | 29943   |  1551.396 |         70.273 |            0.052 |
+------------+---------+-----------+----------------+------------------+
| UP         | 29943   |     2.803 |          0.127 |            0.000 |
+------------+---------+-----------+----------------+------------------+
| Total time |         |  2207.676 |        100.000 |            0.074 |
+------------+---------+-----------+----------------+------------------+

real    57m12.076s
user    21m13.409s
sys 0m9.603s
```

Subsequent run:

```
Total correct = 365 out of 367 documents
Accuracy = 99.4550408719 %

Profiling information for ClassificationModelHTM
+------------+---------+-----------+----------------+------------------+
| Region     | Count   |   Elapsed |   Pct of total |   Secs/iteration |
+============+=========+===========+================+==================+
| classifier | 29943   |   627.119 |         98.698 |            0.021 |
+------------+---------+-----------+----------------+------------------+
| sensor     | 29943   |     5.962 |          0.938 |            0.000 |
+------------+---------+-----------+----------------+------------------+
| UP         | 29943   |     2.308 |          0.363 |            0.000 |
+------------+---------+-----------+----------------+------------------+
| Total time |         |   635.389 |        100.000 |            0.021 |
+------------+---------+-----------+----------------+------------------+

real    20m1.194s
user    19m48.514s
sys 0m7.269s
```

No API requests are made in the subsequent run.

**Comment by BoltzmannBrain** [comment]
Great speedup @oxtopus :smile:

**Comment by subutai** [comment]
@oxtopus Very nice!

**Pull request merged**
